version: 0.0
os: linux

resources:
  - DockerImage:
      Name: ml-project:latest
      ImagePullCredentialsType: SERVICE_ROLE
      
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
