version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to the Docker registry
      - docker login -u partha2064 -p Radhaswami@123
  build:
    commands:
      - echo Building the Docker image
      - docker build -t ml-project .
      - echo tagging docker image
      - docker tag ml-project:latest partha2064/ml-project:latest
  post_build:
    commands:
      - echo Pushing the Docker image to the registry
      - docker push partha2064/ml-project:latest
  
artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: build-artifact-name
  discard-paths: no
